sudo: required
services:
  - docker

berfore_install:
  - docker build -t gandi12/udemy-react-project:latest -f Dockerfile.dev .


script:
  - docker run -e CI=true gandi12/udemy-react-project:latest npm run test
