version: '3'
services:
    gandi-react-web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    gandi-simple-web:
        build:
            context: Simple-Web/
            dockerfile: Dockerfile
        stdin_open: true
        tty: true            
        ports:
            - "3809:8080"

